apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heimdal # Set your desired namespace here

resources:
  - deployment/service-account.yaml
  - deployment/role.yaml
  - deployment/role-binding.yaml
  # Uncomment the following line to enable cluster role binding
  #   NOTE: you can comment out the role and rolebinding if you instead use the cluster role binding
  # - deployment/cluster-role-binding.yaml
  - deployment/service.yaml
  - deployment/ingress.yaml
  - deployment/deployment.yaml

secretGenerator:
  - name: heimdal-creds
    envs:
      - .env
