apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: akeyless-heimdal
build:
  artifacts:
    - image: devorbitus/heimdal
      custom:
        buildCommand: ./custom-build.sh
        dependencies:
          dockerfile:
            path: ./Dockerfile

manifests:
  kustomize:
    paths:
      - .
