apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: python
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: chris.g@akeyless.io # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
