apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heimdal-deploy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heimdal-deploy-role
subjects:
  - kind: ServiceAccount
    name: heimdal-sa
    namespace: python
